RecipeMarket/Models/PrzepisyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecipeMarket.Models
{
    public class PrzepisyViewModel
    {
        public Przepis Przepis { get; set; }
        [Display(Name = "Kategoria")]
        public Kategoria Kategoria { get; set; }

        public IEnumerable<SelectListItem> ListaKategorii { get; set; }
    }

}

RecipeMarket/Controllers/PrzepisyController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RecipeMarket.Models;
using System.Data.Entity;
using RecipeMarket.DAL;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Net;
using System.Net.Mime;

namespace RecipeMarket.Controllers
{
    public class PrzepisyController : Controller
    {
        protected PrzepisyContext db { get; set; }
        protected UserManager<Uzytkownik> userManager { get; set; }

        public PrzepisyController()
        {
            db = new PrzepisyContext();
            userManager = new UserManager<Uzytkownik>(new UserStore<Uzytkownik>(db));
        }



        #region         // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Akcje dla PRZEPISOW - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

       

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przepis przepis = db.Przepisy.First(c => c.PrzepisID == id);

            if (przepis == null)
            {
                return HttpNotFound();
            }

            return View(przepis);
        }

        // GET: Przepisy
        public ActionResult Moje()
        {
            var user = userManager.FindById(User.Identity.GetUserId());
            IQueryable<Przepis> listaPrzepisowUzytkownika = db.Przepisy.Where(m => m.UzytkownikID == user.Id);

            if (listaPrzepisowUzytkownika.Count() > 0)
                return View(listaPrzepisowUzytkownika);
            else
                return View();
        }

        public PrzepisyViewModel PopulateSelectList(PrzepisyViewModel przepisyViewModel)
        {
            List<SelectListItem> listSelectListItem = new List<SelectListItem>();

            foreach (Kategoria kat in db.Kategorie)
            {
                SelectListItem selectListItem = new SelectListItem()
                {
                    Text = kat.NazwaKategorii,
                    Value = kat.KategoriaID.ToString()
                };
                listSelectListItem.Add(selectListItem);
            }


            przepisyViewModel.ListaKategorii = listSelectListItem;

            return przepisyViewModel;

        }

        public ActionResult Create()
        {
            return View(PopulateSelectList(new PrzepisyViewModel()));
        }

        [HttpPost]
        public ActionResult Create(PrzepisyViewModel przepisyViewModel)
        {
            var user = userManager.FindById(User.Identity.GetUserId());

            var przepis = przepisyViewModel.Przepis;

            przepis.DataDodania = DateTime.Now;
            przepis.UzytkownikID = user.Id;

            var kategorie = db.Kategorie.Where(m => m.KategoriaID == przepisyViewModel.Kategoria.KategoriaID).ToList();

            przepisyViewModel.Przepis.Kategorie = kategorie;

            var results = new List<ValidationResult>();
            var context = new ValidationContext(przepis, null, null);

            if (Validator.TryValidateObject(przepis, context, results))
            {
                try
                {
                    db.Przepisy.Add(przepisyViewModel.Przepis);
                    db.SaveChanges();
                    return RedirectToAction("Moje");
                }
                catch (Exception e)
                {
                    return View(PopulateSelectList(przepisyViewModel));
                }

            }

            else
            {


                return View(PopulateSelectList(przepisyViewModel));
            }
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var przepis = db.Przepisy.Find(id);
            if (przepis == null)
            {
                return HttpNotFound();
            }

            var user = userManager.FindById(User.Identity.GetUserId());
            if (user.Id == przepis.UzytkownikID)
            {


                return View(PopulateSelectList(new PrzepisyViewModel() { Przepis = przepis }));
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditConfirmation(PrzepisyViewModel przepisyViewModel)
        {
            var user = userManager.FindById(User.Identity.GetUserId());

            var przepis = przepisyViewModel.Przepis;

            przepis.DataDodania = DateTime.Now;
            przepis.UzytkownikID = user.Id;

            var kategorie = db.Kategorie.Where(m => m.KategoriaID == przepisyViewModel.Kategoria.KategoriaID).ToList();

            przepis.Kategorie.Clear();
            przepis.Kategorie = kategorie;

            var results = new List<ValidationResult>();
            var context = new ValidationContext(przepis, null, null);

            if (Validator.TryValidateObject(przepis, context, results))
            {
                try
                {
                    db.Entry(przepis).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Moje");
                }
                catch (Exception e)
                {
                    return View(PopulateSelectList(przepisyViewModel));
                }

            }

            else
            {


                return View(PopulateSelectList(przepisyViewModel));
            }

        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var przepis = db.Przepisy.Find(id);
            if (przepis == null)
            {
                return HttpNotFound();
            }

            var user = userManager.FindById(User.Identity.GetUserId());
            if (user.Id == przepis.UzytkownikID)
            {
                return View(przepis);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmation(int id)
        {
            var przepis = db.Przepisy.Find(id);
            db.Przepisy.Remove(przepis);
            db.SaveChanges();
            return RedirectToAction("Moje");
        }



        #endregion

        #region         // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Akcje dla KOMENTARZY - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

        public ActionResult CreateComment(int id)
        {
            var komentarz = new Komentarz { PrzepisID = id };

            return View(komentarz);
        }


        [HttpPost]
        public ActionResult CreateComment(Komentarz komentarz)
        {
            var user = userManager.FindById(User.Identity.GetUserId());

            komentarz.DataDodania = DateTime.Now;
            komentarz.UzytkownikID = user.Id;

            if (ModelState.IsValid)
            {
                db.Komentarze.Add(komentarz);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = komentarz.PrzepisID });
            }
            else
            {
                return View(komentarz);
            }
        }

        public ActionResult EditComment(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            var komentarz = db.Komentarze.Find(id);
            if (komentarz == null)
            {
                return HttpNotFound();
            }
            var user = userManager.FindById(User.Identity.GetUserId());
            if (user.Id == komentarz.UzytkownikID)
            {
                return View(komentarz);
            }
            else
            {
                return RedirectToAction("Index", "Home");

            }

        }

        [HttpPost, ActionName("EditComment")]
        [ValidateAntiForgeryToken]
        public ActionResult EditCommentConfirmation(Komentarz komentarz)
        {
            var user = userManager.FindById(User.Identity.GetUserId());

            komentarz.DataDodania = DateTime.Now;
            komentarz.UzytkownikID = user.Id;

            if (ModelState.IsValid)
            {
                db.Entry(komentarz).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = komentarz.PrzepisID });
            }
            else
            {
                return View(komentarz);
            }
        }

        public ActionResult DeleteComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var komentarz = db.Komentarze.Find(id);
            if (komentarz == null)
            {
                return HttpNotFound();
            }
            var user = userManager.FindById(User.Identity.GetUserId());
            if (user.Id == komentarz.UzytkownikID)
            {
                return View(komentarz);
            }
            else
            {
                return RedirectToAction("Index", "Home");

            }

        }

        [HttpPost, ActionName("DeleteComment")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCommentConfirmation(int id)
        {
            var komentarz = db.Komentarze.Find(id);
            db.Komentarze.Remove(komentarz);

RecipeMarket/Views/Przepisy/Create.cshtml
@model RecipeMarket.Models.PrzepisyViewModel

@{
    ViewBag.Title = "Utwórz nowy przepis";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dodaj nowy przepis</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.NazwaPrzepisu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Przepis.NazwaPrzepisu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Przepis.NazwaPrzepisu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.TrescPrzepisu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Przepis.TrescPrzepisu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Przepis.TrescPrzepisu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.CzasPrzygotowania, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Przepis.CzasPrzygotowania, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Przepis.CzasPrzygotowania, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.StopienTrudnosci, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Przepis.StopienTrudnosci, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "1", max = "10" } })
                @Html.ValidationMessageFor(model => model.Przepis.StopienTrudnosci, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.IsPremium, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Przepis.IsPremium)
                    @Html.ValidationMessageFor(model => model.Przepis.IsPremium, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.Kategorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Kategoria.KategoriaID, Model.ListaKategorii, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index", "Home")
</div>

RecipeMarket/Views/Przepisy/CreateComment.cshtml
@model RecipeMarket.Models.Komentarz

@{
    ViewBag.Title = "CreateComment";
}

<h2>Dodaj Komentarz</h2>
<h3>@Model.PrzepisID</h3>

@using (Html.BeginForm("CreateComment", "Przepisy", FormMethod.Post, new { PrzepisID = Model.PrzepisID }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Komentarz</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TrescKomentarza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrescKomentarza, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrescKomentarza, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CzasPrzygotowaniaOK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CzasPrzygotowaniaOK)
                    @Html.ValidationMessageFor(model => model.CzasPrzygotowaniaOK, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StopienTrudnosciOK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.StopienTrudnosciOK)
                    @Html.ValidationMessageFor(model => model.StopienTrudnosciOK, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ocena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ocena, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "1", max = "10" } })
                @Html.ValidationMessageFor(model => model.Ocena, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.Hidden("PrzepisID", Model.PrzepisID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

RecipeMarket/Views/Przepisy/DeleteComment.cshtml
@model RecipeMarket.Models.Komentarz

@{
    ViewBag.Title = "DeleteComment";
}

<h2>Usuń komentarz</h2>

<h3>Jesteś pewien, że chcesz usunąć?</h3>
<div>
    <h4>Komentarz</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Przepis.NazwaPrzepisu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Przepis.NazwaPrzepisu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uzytkownik.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uzytkownik.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrescKomentarza)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrescKomentarza)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDodania)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDodania)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CzasPrzygotowaniaOK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CzasPrzygotowaniaOK)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StopienTrudnosciOK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StopienTrudnosciOK)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ocena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ocena)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Wróć do przepisu", "Details", "Przepisy", new { id = Model.PrzepisID })
        </div>
    }
</div>

RecipeMarket/Views/Przepisy/Details.cshtml
@model RecipeMarket.Models.Przepis

@{
    ViewBag.Title = "Szczegóły";
}

<h2>Szczegóły</h2>


<div class="page-header">
    <h1>
        @Html.DisplayFor(model => model.NazwaPrzepisu)

        @if (Model.Kategorie.FirstOrDefault() == null)
        {
            <small>
                "Brak kategorii
            </small>
        }
        else
        {
            <small>
                @Html.DisplayFor(model => model.Kategorie.FirstOrDefault().NazwaKategorii)
            </small>
        }
    </h1>
    <button class="btn btn-link"><span class="glyphicon glyphicon-chevron-left"></span> @Html.ActionLink("Powrót do Indexu", "Index", "Home")</button>

    @if (HttpContext.Current.User.Identity.Name == Model.Uzytkownicy.UserName)
    {
        <button class="btn btn-primary white-text"><span class="glyphicon glyphicon-edit"></span> @Html.ActionLink("Edycja", "Edit", new { id = Model.PrzepisID }, new { @class = "white-text" })</button>
        <button class="btn btn-danger white-text"><span class="glyphicon glyphicon-trash"></span> @Html.ActionLink("Usuń", "Delete", new { id = Model.PrzepisID }, new { @class = "white-text" })</button>
    }
</div>

<div class="col-md-6">
    <p><strong>@Html.DisplayNameFor(model => model.TrescPrzepisu)</strong> <br /></p>
    <p> @Html.Raw(Model.TrescPrzepisu)</p>
</div>

<div class="col-md-6">
    <div>
        <p><strong>Dodane przez:</strong> @Html.DisplayFor(model => model.Uzytkownicy.Email)</p>

        <p><strong>@Html.DisplayNameFor(model => model.CzasPrzygotowania)</strong> <br /> @Html.DisplayFor(model => model.CzasPrzygotowania)</p>

        <p><strong>@Html.DisplayNameFor(model => model.DataDodania)</strong> <br />@Html.DisplayFor(model => model.DataDodania)</p>

        <p><strong>@Html.DisplayNameFor(model => model.Ocena)</strong> <br />@Html.DisplayFor(model => model.Ocena)</p>

        <p><strong>@Html.DisplayNameFor(model => model.Skladniki)</strong></p>
        <div>
            @foreach (var skladniki in Model.Skladniki)
            {
                <ul>
                    @Html.Raw(skladniki.Ilosc) @Html.Raw(skladniki.Produkt.NazwaProduktu)
                </ul>
            }
        </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h3>
            <small class="pull-right"><strong>@Model.Komentarze.Count</strong></small>
            <strong>Komentarze użytkowników</strong>
        </h3>
    </div><!-- /col-sm-12 -->
</div>

@if (Request.IsAuthenticated)
{
    <div class="form-group">
        <button class="btn btn-success white-text"><span class="glyphicon glyphicon-plus"></span> @Html.ActionLink("Dodaj", "CreateComment", "Przepisy", new { id = Model.PrzepisID }, new { @class = "white-text" })</button>
    </div>
}

@if (Model.Komentarze.FirstOrDefault() == null)
{
    <small>
        Ten przepis nie posiada jeszcze żadnych komentarzy
    </small>
}
else
{



    <br />
    foreach (var komentarz in Model.Komentarze)
    {
        <div class="row">
            <div class="col-sm-1">
                <div class="thumbnail">
                    <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
                </div><!-- /thumbnail -->
            </div><!-- /col-sm-1 -->

            <div class="col-sm-11">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>@komentarz.Uzytkownik.Email</strong> <span class="text-muted">skomentował @komentarz.DataDodania.ToLongDateString(), @komentarz.DataDodania.ToShortTimeString()</span>
                        @if (HttpContext.Current.User.Identity.Name == komentarz.Uzytkownik.UserName)
                        {
                            <div class="pull-right">
                                <button class="btn btn-primary btn-sm white-text"><span class="glyphicon glyphicon-edit"></span> @Html.ActionLink("Edycja", "EditComment", new { id = komentarz.KomentarzID }, new { @class = "white-text" })</button>
                                <button class="btn btn-danger btn-sm white-text"><span class="glyphicon glyphicon-trash"></span> @Html.ActionLink("Usuń", "DeleteComment", new { id = komentarz.KomentarzID }, new { @class = "white-text" })</button>
                            </div>
                        }
                    </div>
                    <div class="panel-body">
                        @komentarz.TrescKomentarza
                    </div><!-- /panel-body -->
                    <div class="panel-footer">
                        <span class="text-muted">
                            Stopień trudności:
                            @if (komentarz.StopienTrudnosciOK)
                            {
                                <strong>OK!</strong>
                            }
                            else
                            {
                                <strong>Błędny</strong>
                            }
                            | Czas przygotowania:
                            @if (komentarz.CzasPrzygotowaniaOK)
                            {
                                <strong>OK!</strong>
                            }
                            else
                            {
                                <strong>Błędny</strong>
                            }
                            <strong class="pull-right"> Ocena: @komentarz.Ocena</strong>

                        </span>
                    </div>
                </div><!-- /panel panel-default -->
            </div><!-- /col-sm-5 -->

        </div>
    }
}

RecipeMarket/Views/Przepisy/Edit.cshtml
@model RecipeMarket.Models.PrzepisyViewModel

@{
    ViewBag.Title = "Edycja Przepisu";
}

<h2>Edycja przepisu</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Przepis.PrzepisID)

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.NazwaPrzepisu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Przepis.NazwaPrzepisu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Przepis.NazwaPrzepisu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.TrescPrzepisu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Przepis.TrescPrzepisu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Przepis.TrescPrzepisu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.CzasPrzygotowania, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Przepis.CzasPrzygotowania, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Przepis.CzasPrzygotowania, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.StopienTrudnosci, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Przepis.StopienTrudnosci, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "1", max = "10" } })
                @Html.ValidationMessageFor(model => model.Przepis.StopienTrudnosci, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.IsPremium, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Przepis.IsPremium)
                    @Html.ValidationMessageFor(model => model.Przepis.IsPremium, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Przepis.Kategorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Kategoria.KategoriaID, Model.ListaKategorii, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Wróć do listy", "Moje", "Przepisy")
</div>

RecipeMarket/Views/Przepisy/Moje.cshtml
@model  IQueryable<RecipeMarket.Models.Przepis>
@{
    ViewBag.Title = "Moje przepisy";
}

<h2>Moje przepisy</h2>
<button class="btn btn-success white-text"><span class="glyphicon glyphicon-plus"></span> @Html.ActionLink("Utwórz", "Create", "Przepisy", new { @class = "white-text" })</button>
<br />

<div class="row">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().NazwaPrzepisu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Kategorie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().DataDodania)
            </th>
            <th></th>
        </tr>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NazwaPrzepisu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kategorie.FirstOrDefault().NazwaKategorii)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataDodania)
                    </td>
                    <td>@Html.ActionLink("Pokaż szczegóły", "Details", "Przepisy", new { id = item.PrzepisID }, null) </td>
                </tr>
            }
        }
    </table>
</div>